# Generated by Django 4.1.3 on 2022-11-10 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="publishers",
            field=models.ManyToManyField(
                related_name="redactors", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
