# Generated by Django 4.1.3 on 2022-11-10 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0002_alter_newspaper_publishers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="publishers",
            field=models.ManyToManyField(
                related_name="newspapers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
